services:
  - type: web
    name: chatgpt-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY_HERE
