services:
  - type: web
    name: all_about_vlsi
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: OPENAI_API_KEY
        value: "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"
